-- SCHOOL DBMS MANAGEMENT SYSTEM
-- TABLE CREATION

CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    GENDER CHAR(1),
    DOB DATE,
    CLASS VARCHAR2(10),
    SECTION CHAR(1),
    ROLL_NO NUMBER,
    PARENT_PHONE VARCHAR2(15)
);

CREATE TABLE EXAM_MARKS (
    MARK_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER,
    EXAM_NAME VARCHAR2(30),
    SUBJECT VARCHAR2(30),
    MARKS NUMBER(3),
    GRADE VARCHAR2(2),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE FEES (
    FEE_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER,
    FEE_TYPE VARCHAR2(30),
    AMOUNT NUMBER(8,2),
    PAYMENT_DATE DATE,
    STATUS VARCHAR2(20),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER,
    ATTENDANCE_DATE DATE,
    STATUS VARCHAR2(10),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE ADMISSION (
    ADMISSION_ID NUMBER PRIMARY KEY,
    STUDENT_ID NUMBER,
    ADMISSION_DATE DATE,
    ADMISSION_CLASS VARCHAR2(10),
    PREVIOUS_SCHOOL VARCHAR2(100),
    ADMISSION_STATUS VARCHAR2(20),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);
