-- SCHOOL DBMS MANAGEMENT SYSTEM
-- Table Creation

CREATE TABLE STUDENT (
    STUDENT_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    GENDER CHAR(1),
    DOB DATE,
    CLASS VARCHAR2(10),
    SECTION CHAR(1),
    ROLL_NO NUMBER,
    PARENT_PHONE VARCHAR2(15)
);
